<a href="https://colab.research.google.com/github/madhu967/Basic-Ml/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1

perform arithmetic operations on NumPy arrays

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])


add = a + b
sub = a - b
mul = a * b
div = a / b

print("Addition:", add)
print("Subtraction:", sub)
print("Multiplication:", mul)
print("Division:", div)

Addition: [2 4 6]
Subtraction: [0 0 0]
Multiplication: [1 4 9]
Division: [1. 1. 1.]


#Question 2
 Write a script to compute the mean and standard deviation of a NumPy array

In [4]:
data = np.array([10, 20, 30, 40, 50])


mean = np.mean(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Standard Deviation:", std_dev)


Mean: 30.0
Standard Deviation: 14.142135623730951


#Question 3
 Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [5]:
array = np.arange(10, 51, 5)
print("Array:", array)

Array: [10 15 20 25 30 35 40 45 50]


#Question 4
Reshape the array into a 2x4 matrix.

In [6]:
array = array[:8]
reshaped_arr = array.reshape(2, 4)
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[10 15 20 25]
 [30 35 40 45]]


#Question 5
 Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
 Extract the sub-matrix containing the last two rows and first two columns.
 Replace all elements greater than 4 with 0.

In [7]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_matrix = array[1:, :2]

array[array > 4] = 0

print("Sub matrix:\n", sub_matrix)
print("Modified Array:\n", array)

Sub matrix:
 [[4 0]
 [0 0]]
Modified Array:
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


#Question 6
 Create two 1D arrays:
a = np.array([1, 2, 3])
 b = np.array([4, 5, 6])
Perform element-wise addition, multiplication, and division.

In [8]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])


add = a + b

mul = a * b
div = a / b

print("Addition:", add)
print("Multiplication:", mul)
print("Division:", div)

Addition: [2 4 6]
Multiplication: [1 4 9]
Division: [1. 1. 1.]


#Question 7
 Create a random NumPy array of size (4, 4). Compute:
 Mean of each column.
Maximum value of the entire array.
Sum of all elements.


In [9]:
ran_array = np.random.rand(4, 4) * 100

print(ran_array)
col_mean = np.mean(ran_array, axis=0)
max_value = np.max(ran_array)
total_sum = np.sum(ran_array)

print("Column Means:", col_mean)
print("Maximum Value:", max_value)
print("Sum of All Elements:", total_sum)

[[67.98982201 16.88200776 72.09791385 56.55876976]
 [14.44662467 66.80847005 62.3341225  20.16932393]
 [50.2366677  55.82977233 38.35284565 28.9311775 ]
 [80.12974647 58.54356078 28.15432614 19.00210416]]
Column Means: [53.20071522 49.51595273 50.23480203 31.16534384]
Maximum Value: 80.12974647269274
Sum of All Elements: 736.4672552772604


#Question 8
Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2.

In [10]:
array = np.array([[1, 2, 3, 4], [5,6,7,8]])

result_array = (array + 10) * 2
print("Modified Array:\n", result_array)

Modified Array:
 [[22 24 26 28]
 [30 32 34 36]]


#Question 9
Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
 1 to 100. Perform the following:
Extract the second "layer" (i.e., the second 2D array) in the first dimension.
 Extract the first two rows and the last three columns from each "layer."
 Replace all elements divisible by 3 with -1.

In [11]:
array = np.random.randint(1, 101, (3, 4, 5))

second_layer = array[1]

sub_matrix = array[:, :2, -3:]

array[array % 3 == 0] = -1

print("Second Layer:\n", second_layer)
print("Sub-matrix:\n", sub_matrix)
print("Modified Array:\n", array)

Second Layer:
 [[-1 -1 34 14 -1]
 [50 26 16 64  1]
 [82 -1 -1 62 -1]
 [94 76 29 -1 -1]]
Sub-matrix:
 [[[ -1  40  40]
  [ -1  22  -1]]

 [[ 34  14  -1]
  [ 16  64   1]]

 [[ -1  98 100]
  [ -1  -1  62]]]
Modified Array:
 [[[  7  34  -1  40  40]
  [ -1  -1  -1  22  -1]
  [ 77  -1  -1  13  -1]
  [ 88  23  25  -1  32]]

 [[ -1  -1  34  14  -1]
  [ 50  26  16  64   1]
  [ 82  -1  -1  62  -1]
  [ 94  76  29  -1  -1]]

 [[ 52  -1  -1  98 100]
  [ -1  49  -1  -1  62]
  [ 38  -1  55  97  98]
  [ 77  -1  50  -1  89]]]


#Question 10
 Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
Subtract the mean of each row from its respective elements (row-wise
normalization).
Create a new array by squaring all the elements in arr.
 Find the indices of the top 3 maximum values in the entire array


In [12]:
arr = np.random.randint(1, 21, (3, 3))

row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means

squared_arr = arr ** 2


flattened_indices = np.argsort(arr.ravel())[-3:]

indices = [np.unravel_index(idx, arr.shape) for idx in flattened_indices]

print("Original Array:\n", arr)
print("Row-wise Normalized Array:\n", normalized_arr)
print("Squared Array:\n", squared_arr)
print("Indices of Top 3 Maximum Values:", indices)

Original Array:
 [[11  6  7]
 [14  5 11]
 [ 2  6  2]]
Row-wise Normalized Array:
 [[ 3.         -2.         -1.        ]
 [ 4.         -5.          1.        ]
 [-1.33333333  2.66666667 -1.33333333]]
Squared Array:
 [[121  36  49]
 [196  25 121]
 [  4  36   4]]
Indices of Top 3 Maximum Values: [(0, 0), (1, 2), (1, 0)]
